### ISSUE TITLE
无法收到注册邮件

### ISSUE THREAD

**Issue by xiaoquisme** [EchoAnde/nutshell_blog#2]
你的网站上没有找到反馈的联系方式，所以到这里来反馈一下。
我注册用户分别输入了Gmai 的邮箱地址和QQ的邮箱地址都没有收到注册邮件。可否解决这个问题。

**Comment by dotnetcore-group** [comment]
谢谢你的反馈。是的，我注意到了这个问题。主要是发布到服务器上后就无法发送验证邮件，在本地调试是可以的。我现在也不知道是什么问题，如果你知道怎么解决请告诉我，谢谢！

**Comment by xiaoquisme** [comment]
你的服务器用的是windows的还是Linux的？

**Comment by dotnetcore-group** [comment]
windows server 2008

**Comment by zengande** [comment]
服务器申请25端口解封
